# Generated by Django 2.0.6 on 2018-06-28 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Report Name', max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Scan Name', max_length=20)),
                ('description', models.CharField(help_text='scanner function', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('fiftyTwoWkHigh', models.FloatField()),
                ('fiftyTwoWkLow', models.FloatField()),
                ('avgVolume', models.FloatField()),
                ('twentyDayAvgVol', models.FloatField()),
                ('exchange', models.CharField(max_length=20)),
                ('lastPrice', models.FloatField()),
                ('netChange', models.FloatField()),
                ('percentChange', models.FloatField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('volume', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Scan'),
        ),
        migrations.AddField(
            model_name='report',
            name='stocks',
            field=models.ManyToManyField(to='reports.Stock'),
        ),
    ]
