# Generated by Django 2.0.6 on 2018-07-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20180702_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='stocks',
            field=models.ManyToManyField(blank=True, to='reports.Stock'),
        ),
    ]
