# Generated by Django 2.0.6 on 2018-07-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20180702_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='last_update',
            field=models.DateTimeField(),
        ),
    ]
