# Generated by Django 2.0.6 on 2018-07-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_stock_one_yr_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_a_value_scan',
            field=models.BooleanField(default=True),
        ),
    ]
