# Generated by Django 2.0.6 on 2018-07-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_report_is_a_value_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='revenue_growth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
