# Generated by Django 2.0.6 on 2018-07-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_stock_revenue_growth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_update',
            field=models.DateTimeField(),
        ),
    ]
