# Generated by Django 2.0.6 on 2018-07-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20180722_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
