# Generated by Django 2.0.6 on 2018-07-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_stock_compositemetric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='compositeMetric',
            new_name='composite_Metric',
        ),
    ]
